spring.application.name=tfgapp
spring.datasource.url=jdbc:mysql://localhost:3310/tfgapp_db
spring.datasource.username=rmgadmin
spring.datasource.password=africa

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000



# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#profile
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Session
jwt.secret=${JWT_SECRET:miClaveSuperLargaSeguraCon256bits!!!1234567890}
jwt.expiration=${JWT_EXPIRATION:3600000}
